### ISSUE TITLE
Puma 5.0 beta TODO

### ISSUE THREAD

**Issue by nateberkopec** [puma/puma#2255]
* [x] Tidy up `HISTORY.md`
* [x] Write `5.0-Upgrade.md`
* [x] Change version constants
* [x] Make sure we understand the upgrade path completely and what behavior changes by default (thinking about GC compact)
* [x] Try upgrading a handful of apps
* [x] Create an issue for tracking the result of the experimental features
* [x] Release

**Comment by nateberkopec** [comment]
5.0 upgrade file needs descriptions about how to use and evaluate the new performance features. I'm also wondering if we should go further with GC.compact before fork and also nakayoshi-fork, or gate it behind an option for now.

**Comment by nateberkopec** [comment]
5.0.0-beta1 is pushed to RG: https://rubygems.org/gems/puma/versions/5.0.0.beta1
